In [20]:
import numpy as np
import pandas as pd

In [21]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = pd.read_csv(url, names=names)

In [22]:
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [23]:
X = dataset.drop('Class', 1)
y = dataset['Class']

<ipython-input-23-a134714d2c8b>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = dataset.drop('Class', 1)


In [24]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [25]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [26]:
from sklearn.decomposition import PCA

pca0 = PCA()
X_train0 = pca0.fit_transform(X_train)
X_test0 = pca0.transform(X_test)

In [27]:
explained_variance = pca0.explained_variance_ratio_

In [29]:
from sklearn.decomposition import PCA

pca1 = PCA(n_components=1)
X_train1 = pca1.fit_transform(X_train)
X_test1 = pca1.transform(X_test)

In [30]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train1, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test1)

In [31]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[11  0  0]
 [ 0 12  1]
 [ 0  1  5]]
Accuracy0.9333333333333333


In [32]:
from sklearn.decomposition import PCA

pca2 = PCA(n_components=2)
X_train2 = pca2.fit_transform(X_train)
X_test2 = pca2.transform(X_test)

In [34]:
from sklearn.ensemble import RandomForestClassifier

classifier2 = RandomForestClassifier(max_depth=2, random_state=0)
classifier2.fit(X_train2, y_train)

# Predicting the Test set results
y_pred2 = classifier2.predict(X_test2)

In [35]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm2 = confusion_matrix(y_test, y_pred2)
print(cm2)
print('Accuracy' + str(accuracy_score(y_test, y_pred2)))

[[11  0  0]
 [ 0  9  4]
 [ 0  2  4]]
Accuracy0.8


In [36]:
#with 3 principal compoments
from sklearn.decomposition import PCA

pca3 = PCA(n_components=3)
X_train3 = pca3.fit_transform(X_train)
X_test3 = pca3.transform(X_test)

In [37]:
from sklearn.ensemble import RandomForestClassifier

classifier3 = RandomForestClassifier(max_depth=2, random_state=0)
classifier3.fit(X_train3, y_train)

# Predicting the Test set results
y_pred3 = classifier3.predict(X_test3)

In [38]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm3 = confusion_matrix(y_test, y_pred3)
print(cm3)
print('Accuracy' + str(accuracy_score(y_test, y_pred3)))

[[11  0  0]
 [ 0  8  5]
 [ 0  1  5]]
Accuracy0.8
